language: python
python:
  - "3.6"
cache: pip
install:
  - pip install -r requirements.txt
script:
  - python -m unittest discover -v
  - coverage run  -m unittest discover
  - coverage report  monitor_promdiscovery/*
  - python setup.py sdist

before_deploy:
  - export RELEASE_PKG_FILE=$(ls dist/monitor-promdiscovery-*.tar.gz)
  - echo "deploying $RELEASE_PKG_FILE to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_ACCESS_TOKEN
  file_glob: true
  file: "${RELEASE_PKG_FILE}"
  skip_cleanup: true
  on:
    tags: true
