op5monitor:
  url: https://monitor.aw.oc-testbench.xyz
  user: monitor
  passwd: monitor
  # The hostgroup used to select hosts as targets
  hostgroup: prometheus

prometheus:
  sd_file: /home/andersh/programs/prometheus/sd/monitor_sd.yml
  labels:
    source: monitor
    env: prod

logger:
  # Path and name for the log file. If not set sent to stdout
  logfile: /home/andersh/opsdisgit/monitor-promdiscovery/monitor-promdiscovery
  # Format
  # format: day
  # Log level
  #level: INFO