op5monitor:
  url: https://monitor.local
  user: monitor
  passwd: monitor
  # The hostgroup used to select hosts as targets
  hostgroup: prometheus

prometheus:
  # path where to create the file-based discovery file
  sd_file: <sd_directory>/monitor_sd.yml
  # Additional labels to tag metrics with
  labels:
    source: monitor
    env: prod

logger:
  # Path and name for the log file. If not set sent to stdout
  logfile: monitor-promdiscovery
  # Format if day will have current day as post fix
  # format: day
  # Log level
  #level: INFO